wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1670333151.952903
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      3:
      - 13
      - 15
      - 23
      4: 3.9.15
      5: 0.13.5
      6: 4.25.1
      8:
      - 1
      - 5
distributed:
  desc: null
  value:
    mixed_precision: 'no'
    num_gpus: 1
method:
  desc: null
  value:
    chunk_size: 128
    cliprange: 0.2
    cliprange_reward: 10
    cliprange_value: 0.2
    gamma: 1
    gen_kwargs:
      do_sample: true
      max_length: 48
      min_length: 48
      top_k: 0.0
      top_p: 1.0
    horizon: 10000
    init_kl_coef: 0.05
    lam: 0.95
    name: ppoconfig
    num_rollouts: 128
    ppo_epochs: 4
    ref_mean: null
    ref_std: null
    scale_reward: false
    target: 6
    vf_coef: 1
model:
  desc: null
  value:
    model_path: lvwerra/gpt2-imdb
    model_type: AcceleratePPOModel
    num_layers_unfrozen: 2
    tokenizer_path: gpt2
train:
  desc: null
  value:
    batch_size: 128
    checkpoint_dir: ckpts
    checkpoint_interval: 10000
    entity_name: null
    epochs: 100
    eval_interval: 100
    lr_init: 0.0001
    lr_target: 0.0001
    opt_betas:
    - 0.9
    - 0.95
    opt_eps: 1.0e-08
    orchestrator: PPOOrchestrator
    pipeline: PromptPipeline
    project_name: trlx
    rollout_logging_dir: null
    seed: 1000
    seq_length: 48
    total_steps: 10000
    weight_decay: 1.0e-06
